# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1035, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.locationsViewTab = QtWidgets.QWidget()
        self.locationsViewTab.setObjectName("locationsViewTab")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.locationsViewTab)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.locationsSelectView = QtWidgets.QListWidget(self.locationsViewTab)
        self.locationsSelectView.setObjectName("locationsSelectView")
        self.horizontalLayout_7.addWidget(self.locationsSelectView)
        self.itemsSelectView = QtWidgets.QListWidget(self.locationsViewTab)
        self.itemsSelectView.setObjectName("itemsSelectView")
        self.horizontalLayout_7.addWidget(self.itemsSelectView)
        self.frame_9 = QtWidgets.QFrame(self.locationsViewTab)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame_9)
        self.formLayout_2.setObjectName("formLayout_2")
        self.itemPriceView = QtWidgets.QLineEdit(self.frame_9)
        self.itemPriceView.setReadOnly(True)
        self.itemPriceView.setObjectName("itemPriceView")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.itemPriceView)
        self.label_5 = QtWidgets.QLabel(self.frame_9)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.itemNameView = QtWidgets.QLineEdit(self.frame_9)
        self.itemNameView.setReadOnly(True)
        self.itemNameView.setObjectName("itemNameView")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.itemNameView)
        self.label_6 = QtWidgets.QLabel(self.frame_9)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(2, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.horizontalLayout_7.addWidget(self.frame_9)
        self.tabWidget.addTab(self.locationsViewTab, "")
        self.locationsTab = QtWidgets.QWidget()
        self.locationsTab.setObjectName("locationsTab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.locationsTab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_10 = QtWidgets.QFrame(self.locationsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_12 = QtWidgets.QFrame(self.frame_10)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.frame_12)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.locationNameEdit = QtWidgets.QLineEdit(self.frame_12)
        self.locationNameEdit.setObjectName("locationNameEdit")
        self.horizontalLayout_9.addWidget(self.locationNameEdit)
        self.verticalLayout_5.addWidget(self.frame_12)
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.newLocation = QtWidgets.QPushButton(self.frame_11)
        self.newLocation.setObjectName("newLocation")
        self.horizontalLayout_8.addWidget(self.newLocation)
        self.deleteLocation = QtWidgets.QPushButton(self.frame_11)
        self.deleteLocation.setObjectName("deleteLocation")
        self.horizontalLayout_8.addWidget(self.deleteLocation)
        self.verticalLayout_5.addWidget(self.frame_11)
        self.locationSelection = QtWidgets.QListWidget(self.frame_10)
        self.locationSelection.setObjectName("locationSelection")
        self.verticalLayout_5.addWidget(self.locationSelection)
        self.horizontalLayout.addWidget(self.frame_10)
        self.frame_8 = QtWidgets.QFrame(self.locationsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_13 = QtWidgets.QFrame(self.frame_8)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_7 = QtWidgets.QLabel(self.frame_13)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        self.modifierEdit = QtWidgets.QLineEdit(self.frame_13)
        self.modifierEdit.setObjectName("modifierEdit")
        self.horizontalLayout_11.addWidget(self.modifierEdit)
        self.verticalLayout_6.addWidget(self.frame_13)
        self.frame_7 = QtWidgets.QFrame(self.frame_8)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.locationModifierSelection = QtWidgets.QListWidget(self.frame_7)
        self.locationModifierSelection.setObjectName("locationModifierSelection")
        self.verticalLayout_4.addWidget(self.locationModifierSelection)
        self.verticalLayout_6.addWidget(self.frame_7)
        self.horizontalLayout.addWidget(self.frame_8)
        self.tabWidget.addTab(self.locationsTab, "")
        self.itemsTab = QtWidgets.QWidget()
        self.itemsTab.setObjectName("itemsTab")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.itemsTab)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_4 = QtWidgets.QFrame(self.itemsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.formLayout = QtWidgets.QFormLayout(self.frame_6)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_6)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.itemNameEdit = QtWidgets.QLineEdit(self.frame_6)
        self.itemNameEdit.setObjectName("itemNameEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.itemNameEdit)
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.itemBasePrice = QtWidgets.QLineEdit(self.frame_6)
        self.itemBasePrice.setObjectName("itemBasePrice")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.itemBasePrice)
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.itemGroupSelect = QtWidgets.QListWidget(self.frame_6)
        self.itemGroupSelect.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.itemGroupSelect.setObjectName("itemGroupSelect")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.itemGroupSelect)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.newItem = QtWidgets.QPushButton(self.frame_5)
        self.newItem.setObjectName("newItem")
        self.horizontalLayout_5.addWidget(self.newItem)
        self.deleteItem = QtWidgets.QPushButton(self.frame_5)
        self.deleteItem.setObjectName("deleteItem")
        self.horizontalLayout_5.addWidget(self.deleteItem)
        self.verticalLayout_3.addWidget(self.frame_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_6.addWidget(self.frame_4)
        self.itemEditView = QtWidgets.QListWidget(self.itemsTab)
        self.itemEditView.setObjectName("itemEditView")
        self.horizontalLayout_6.addWidget(self.itemEditView)
        self.tabWidget.addTab(self.itemsTab, "")
        self.groupsTab = QtWidgets.QWidget()
        self.groupsTab.setObjectName("groupsTab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupsTab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.groupsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.groupNameEdit = QtWidgets.QLineEdit(self.frame_2)
        self.groupNameEdit.setObjectName("groupNameEdit")
        self.horizontalLayout_3.addWidget(self.groupNameEdit)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.newGroup = QtWidgets.QPushButton(self.frame_3)
        self.newGroup.setObjectName("newGroup")
        self.horizontalLayout_4.addWidget(self.newGroup)
        self.deleteGroup = QtWidgets.QPushButton(self.frame_3)
        self.deleteGroup.setObjectName("deleteGroup")
        self.horizontalLayout_4.addWidget(self.deleteGroup)
        self.verticalLayout_2.addWidget(self.frame_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2.addWidget(self.frame)
        self.groupEditView = QtWidgets.QListWidget(self.groupsTab)
        self.groupEditView.setObjectName("groupEditView")
        self.horizontalLayout_2.addWidget(self.groupEditView)
        self.tabWidget.addTab(self.groupsTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "Item"))
        self.label_6.setText(_translate("MainWindow", "Price"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.locationsViewTab), _translate("MainWindow", "Locations view"))
        self.label_8.setText(_translate("MainWindow", "Name"))
        self.newLocation.setText(_translate("MainWindow", "New"))
        self.deleteLocation.setText(_translate("MainWindow", "Delete"))
        self.label_7.setText(_translate("MainWindow", "Modifier"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.locationsTab), _translate("MainWindow", "Locations"))
        self.label_2.setText(_translate("MainWindow", "Name"))
        self.label_3.setText(_translate("MainWindow", "Base price"))
        self.label_4.setText(_translate("MainWindow", "Groups"))
        self.newItem.setText(_translate("MainWindow", "New"))
        self.deleteItem.setText(_translate("MainWindow", "Delete"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.itemsTab), _translate("MainWindow", "Items"))
        self.label.setText(_translate("MainWindow", "Name"))
        self.newGroup.setText(_translate("MainWindow", "New"))
        self.deleteGroup.setText(_translate("MainWindow", "Delete"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.groupsTab), _translate("MainWindow", "Groups"))
